# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: blog.samake.se

site_dir: public

site_url: https://blog.samake.se

theme:
  name: material
  custom_dir: overrides
  font:
    text: Hanken Grotesk
  features:
    - header.autohide
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - content.action.edit
    - navigation.sections
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      toggle:
        icon: octicons/moon-16
        name: Switch to light mode

extra_css:
  - extra.css

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://samake.se

plugins:
  - blog:
      blog_dir: .
  - search
  - tags
  - open-in-new-tab

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
